version: '2'

services:
  nginx:
    build: ./nginx
    depends_on:
      - noaa-api-0
      - noaa-goes-api-1
      - web-api-1
      - web-api-2
      - web-dash-1
      - web-dash-2
    ports:
      - "${WEB_PORT}:80"
  mongo:
    build: ./mongo
    image: "dendro:mongo"
    ports:
      - "${MONGO_PORT}:27017"
    entrypoint: /auth-entrypoint.sh
    command: mongod
    environment:
      - MONGO_ADMIN_USER
      - MONGO_ADMIN_PASS
      - MONGO_DB_NAME
      - MONGO_DB_USER
      - MONGO_DB_PASS
    volumes:
      - "${MONGO_DB_VOLUME}"
  migrations:
    depends_on:
      - mongo
    image: "dendro/dendro-migrations"
    environment:
      - MONGO_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongo:27017/${MONGO_DB_NAME}
  noaa-api-0:
    image: "dendro/dendro-noaa-api"
  noaa-goes-api-1:
    image: "dendro/dendra-noaa-goes-api"
    environment:
      - NOAA_GOES_DDS_USER
      - NOAA_GOES_DDS_PASS
  web-api-1:
    depends_on:
      - mongo
    image: "dendro/dendro-web-api"
    environment:
      - LEGACY_MYSQL_URL
      - MONGO_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongo:27017/${MONGO_DB_NAME}
      - NOAA_API_URL=http://noaa-api-0:8080
  web-api-2:
    depends_on:
      - mongo
    image: "dendro/dendro-web-api"
    environment:
      - LEGACY_MYSQL_URL
      - MONGO_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongo:27017/${MONGO_DB_NAME}
      - NOAA_API_URL=http://noaa-api-0:8080
  web-dash-1:
    image: "dendro/dendro-web-dash"
  web-dash-2:
    image: "dendro/dendro-web-dash"
