version: '2'

services:
  nginx:
    build: ./nginx
    depends_on:
      - noaa-api-0
      - noaa-goes-api-1
      - web-api-1
      - web-api-2
      - web-dash-1
      - web-dash-2
    ports:
      - "${WEB_PORT}:80"
  influxdb:
    build: ./influxdb
    image: "dendro:influxdb"
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - "${INFLUXDB_VOLUME}"
  mongo:
    build: ./mongo
    image: "dendro:mongo"
    ports:
      - "${MONGO_PORT}:27017"
    entrypoint: /auth-entrypoint.sh
    command: mongod
    environment:
      - MONGO_ADMIN_USER
      - MONGO_ADMIN_PASS
      - MONGO_DB_NAME
      - MONGO_DB_USER
      - MONGO_DB_PASS
    volumes:
      - "${MONGO_DB_VOLUME}"
  migrations:
    depends_on:
      - mongo
    image: "dendro/dendra-mongo-migrations"
    environment:
      - MONGO_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongo:27017/${MONGO_DB_NAME}
  noaa-api-0:
    image: "dendro/dendra-noaa-nws-api"
  noaa-goes-api-1:
    image: "dendro/dendra-noaa-goes-api"
    environment:
      - NOAA_GOES_DDS_USER
      - NOAA_GOES_DDS_PASS
  json-archive-api-1:
    image: "dendro/dendra-json-archive-api"
    volumes:
      - "${JSON_ARCHIVE_VOLUME}"
  csi-worker:
    build: ./csi-worker
    image: "dendro:csi-worker"
    depends_on:
      - influxdb
      - json-archive-api-1
    environment:
      - CSI_LDMP_HOST
      - CSI_LDMP_PORT
      - INFLUXDB_API_URL=http://influxdb:${INFLUXDB_PORT}
      - JSON_ARCHIVE_API_URL=http://json-archive-api-1:8080
    volumes:
      - "${CSI_WORKER_VOLUME}"
  goes-worker:
    build: ./goes-worker
    image: "dendro:goes-worker"
    depends_on:
      - influxdb
      - json-archive-api-1
      - noaa-goes-api-1
    environment:
      - INFLUXDB_API_URL=http://influxdb:${INFLUXDB_PORT}
      - JSON_ARCHIVE_API_URL=http://json-archive-api-1:8080
      - NOAA_GOES_API_URL=http://noaa-goes-api-1:8080
    volumes:
      - "${GOES_WORKER_VOLUME}"
  web-api-1:
    depends_on:
      - mongo
    image: "dendro/dendra-web-api"
    environment:
      - INFLUXDB_API_URL=http://influxdb:${INFLUXDB_PORT}
      - LEGACY_MYSQL_URL
      - MONGO_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongo:27017/${MONGO_DB_NAME}
      - NOAA_GOES_API_URL=http://noaa-goes-api-1:8080
      - NOAA_NWS_API_URL=http://noaa-api-0:8080
      - NOAA_API_URL=http://noaa-api-0:8080
      - WEB_API_SECRET
  web-api-2:
    depends_on:
      - mongo
    image: "dendro/dendra-web-api"
    environment:
      - INFLUXDB_API_URL=http://influxdb:${INFLUXDB_PORT}
      - LEGACY_MYSQL_URL
      - MONGO_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongo:27017/${MONGO_DB_NAME}
      - NOAA_GOES_API_URL=http://noaa-goes-api-1:8080
      - NOAA_NWS_API_URL=http://noaa-api-0:8080
      - NOAA_API_URL=http://noaa-api-0:8080
      - WEB_API_SECRET
  web-dash-1:
    image: "dendro/dendro-web-dash"
    environment:
      - WEB_DASH_API_PATH
      - WEB_DASH_API_URI
  web-dash-2:
    image: "dendro/dendro-web-dash"
    environment:
      - WEB_DASH_API_PATH
      - WEB_DASH_API_URI
